services:
    uwb_localization:
        container_name: uwb_localization
        hostname: uwb_localization
        image: hf/uwb_px4_sim:latest
        runtime: nvidia
        command: ./start.sh
        build:
            dockerfile: Dockerfile
        environment:
            - DISPLAY=${DISPLAY}
            - ROS_MASTER_IP=http://localhost:11311 
            - ROS_IP=127.0.0.1
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - $PWD:/home/docker/ws/src/uwb_localization:rw
            - $PWD/start.sh:/home/docker/ws/start.sh:rw
        privileged: true
        network_mode: host
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]