services:
    sim:
        container_name: sim
        hostname: sim
        image: hf/uwb_px4_sim:latest
        command: gazebo
        build:
            dockerfile: Dockerfile
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
        privileged: true
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]